server.port=${PORT:8080}

# --- Supabase Database Configuration ---
spring.datasource.url=jdbc:postgresql://${SUPABASE_DB_HOST:aws-1-ap-southeast-1.pooler.supabase.com}:5432/postgres?sslmode=require
spring.datasource.username=${SUPABASE_DB_USER:postgres.oslhmctcqgszovthxjwx}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# connection pool limits for Supabase
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

logging.level.com.kaveri=INFO
groq.api.key={GROQ.API.KEY}
groq.api.url={GROQ.API.URL}
groq.api.model={GROQ.API..MODEL}
